module Evergreen.Migrate.V10 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V10.Types
import Evergreen.V9.Types
import Lamdera.Migrations exposing (..)
import List
import SeqSet


frontendModel : Evergreen.V9.Types.FrontendModel -> ModelMigration Evergreen.V10.Types.FrontendModel Evergreen.V10.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V9.Types.BackendModel -> ModelMigration Evergreen.V10.Types.BackendModel Evergreen.V10.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V9.Types.FrontendMsg -> MsgMigration Evergreen.V10.Types.FrontendMsg Evergreen.V10.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V9.Types.ToBackend -> MsgMigration Evergreen.V10.Types.ToBackend Evergreen.V10.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V9.Types.BackendMsg -> MsgMigration Evergreen.V10.Types.BackendMsg Evergreen.V10.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V9.Types.ToFrontend -> MsgMigration Evergreen.V10.Types.ToFrontend Evergreen.V10.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V9.Types.FrontendModel -> Evergreen.V10.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , rows = old.rows
    , cols = old.cols
    , cells = old.cells
    , headerAlignments = old.headerAlignments |> Dict.map (\k -> migrate_Types_Alignment)
    , bodyAlignments = old.bodyAlignments |> Dict.map (\k -> migrate_Types_Alignment)
    , horizontalLineStyles = old.horizontalLineStyles |> Dict.map (\k -> migrate_Types_LineStyle)
    , verticalLineStyles = old.verticalLineStyles |> Dict.map (\k -> migrate_Types_LineStyle)
    , cellHorizontalStyles = old.cellHorizontalStyles |> Dict.map (\k -> migrate_Types_LineStyle)
    , cellVerticalStyles = old.cellVerticalStyles |> Dict.map (\k -> migrate_Types_LineStyle)
    , outputFormat = old.outputFormat |> migrate_Types_OutputFormat
    , showImport = old.showImport
    , importText = old.importText
    , collapsedSections = old.collapsedSections |> SeqSet.map migrate_Types_OutputSection
    , undoStack = old.undoStack |> List.map migrate_Types_TableSnapshot
    , sortState = old.sortState |> migrate_Types_SortState
    , summaryRows = old.summaryRows |> SeqSet.map migrate_Types_SummaryFunction
    , summarySeparatorStyles = old.summarySeparatorStyles |> Dict.map (\k -> migrate_Types_LineStyle)
    }


migrate_Types_Alignment : Evergreen.V9.Types.Alignment -> Evergreen.V10.Types.Alignment
migrate_Types_Alignment old =
    case old of
        Evergreen.V9.Types.AlignLeft ->
            Evergreen.V10.Types.AlignLeft

        Evergreen.V9.Types.AlignCenter ->
            Evergreen.V10.Types.AlignCenter

        Evergreen.V9.Types.AlignRight ->
            Evergreen.V10.Types.AlignRight


migrate_Types_FrontendMsg : Evergreen.V9.Types.FrontendMsg -> Evergreen.V10.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V9.Types.UrlClicked p0 ->
            Evergreen.V10.Types.UrlClicked p0

        Evergreen.V9.Types.UrlChanged p0 ->
            Evergreen.V10.Types.UrlChanged p0

        Evergreen.V9.Types.CellChanged p0 p1 p2 ->
            Evergreen.V10.Types.CellChanged p0 p1 p2

        Evergreen.V9.Types.AddRow ->
            Evergreen.V10.Types.AddRow

        Evergreen.V9.Types.AddColumn ->
            Evergreen.V10.Types.AddColumn

        Evergreen.V9.Types.RemoveRow p0 ->
            Evergreen.V10.Types.RemoveRow p0

        Evergreen.V9.Types.RemoveColumn p0 ->
            Evergreen.V10.Types.RemoveColumn p0

        Evergreen.V9.Types.InsertRow p0 ->
            Evergreen.V10.Types.InsertRow p0

        Evergreen.V9.Types.InsertColumn p0 ->
            Evergreen.V10.Types.InsertColumn p0

        Evergreen.V9.Types.SetOutputFormat p0 ->
            Evergreen.V10.Types.SetOutputFormat (p0 |> migrate_Types_OutputFormat)

        Evergreen.V9.Types.SetHeaderAlignment p0 p1 ->
            Evergreen.V10.Types.SetHeaderAlignment p0 (p1 |> migrate_Types_Alignment)

        Evergreen.V9.Types.SetBodyAlignment p0 p1 ->
            Evergreen.V10.Types.SetBodyAlignment p0 (p1 |> migrate_Types_Alignment)

        Evergreen.V9.Types.ToggleImport ->
            Evergreen.V10.Types.ToggleImport

        Evergreen.V9.Types.ImportTextChanged p0 ->
            Evergreen.V10.Types.ImportTextChanged p0

        Evergreen.V9.Types.ImportData ->
            Evergreen.V10.Types.ImportData

        Evergreen.V9.Types.CycleHorizontalLineStyle p0 ->
            Evergreen.V10.Types.CycleHorizontalLineStyle p0

        Evergreen.V9.Types.CycleVerticalLineStyle p0 ->
            Evergreen.V10.Types.CycleVerticalLineStyle p0

        Evergreen.V9.Types.CycleCellHorizontalStyle p0 p1 ->
            Evergreen.V10.Types.CycleCellHorizontalStyle p0 p1

        Evergreen.V9.Types.CycleCellVerticalStyle p0 p1 ->
            Evergreen.V10.Types.CycleCellVerticalStyle p0 p1

        Evergreen.V9.Types.ToggleSection p0 ->
            Evergreen.V10.Types.ToggleSection (p0 |> migrate_Types_OutputSection)

        Evergreen.V9.Types.Undo ->
            Evergreen.V10.Types.Undo

        Evergreen.V9.Types.SetSortColumn p0 ->
            Evergreen.V10.Types.SetSortColumn p0

        Evergreen.V9.Types.SetSortDirection p0 ->
            Evergreen.V10.Types.SetSortDirection (p0 |> migrate_Types_SortDirection)

        Evergreen.V9.Types.SetSortMethod p0 ->
            Evergreen.V10.Types.SetSortMethod (p0 |> migrate_Types_SortMethod)

        Evergreen.V9.Types.ApplySortToInputs ->
            Evergreen.V10.Types.ApplySortToInputs

        Evergreen.V9.Types.ToggleSummaryRow p0 ->
            Evergreen.V10.Types.ToggleSummaryRow (p0 |> migrate_Types_SummaryFunction)

        Evergreen.V9.Types.CycleSummarySeparatorStyle p0 ->
            Evergreen.V10.Types.CycleSummarySeparatorStyle p0


migrate_Types_LineStyle : Evergreen.V9.Types.LineStyle -> Evergreen.V10.Types.LineStyle
migrate_Types_LineStyle old =
    case old of
        Evergreen.V9.Types.None ->
            Evergreen.V10.Types.None

        Evergreen.V9.Types.Thin ->
            Evergreen.V10.Types.Thin

        Evergreen.V9.Types.Thick ->
            Evergreen.V10.Types.Thick

        Evergreen.V9.Types.ThinTripleDash ->
            Evergreen.V10.Types.ThinTripleDash

        Evergreen.V9.Types.ThickTripleDash ->
            Evergreen.V10.Types.ThickTripleDash

        Evergreen.V9.Types.ThinQuadDash ->
            Evergreen.V10.Types.ThinQuadDash

        Evergreen.V9.Types.ThickQuadDash ->
            Evergreen.V10.Types.ThickQuadDash

        Evergreen.V9.Types.ThinDoubleDash ->
            Evergreen.V10.Types.ThinDoubleDash

        Evergreen.V9.Types.ThickDoubleDash ->
            Evergreen.V10.Types.ThickDoubleDash

        Evergreen.V9.Types.Double ->
            Evergreen.V10.Types.Double


migrate_Types_OutputFormat : Evergreen.V9.Types.OutputFormat -> Evergreen.V10.Types.OutputFormat
migrate_Types_OutputFormat old =
    case old of
        Evergreen.V9.Types.Compact ->
            Evergreen.V10.Types.Compact

        Evergreen.V9.Types.Expanded ->
            Evergreen.V10.Types.Expanded


migrate_Types_OutputSection : Evergreen.V9.Types.OutputSection -> Evergreen.V10.Types.OutputSection
migrate_Types_OutputSection old =
    case old of
        Evergreen.V9.Types.BoxDrawingSection ->
            Evergreen.V10.Types.BoxDrawingSection

        Evergreen.V9.Types.MarkdownSection ->
            Evergreen.V10.Types.MarkdownSection

        Evergreen.V9.Types.PreviewSection ->
            Evergreen.V10.Types.PreviewSection

        Evergreen.V9.Types.HtmlSection ->
            Evergreen.V10.Types.HtmlSection


migrate_Types_SortDirection : Evergreen.V9.Types.SortDirection -> Evergreen.V10.Types.SortDirection
migrate_Types_SortDirection old =
    case old of
        Evergreen.V9.Types.Ascending ->
            Evergreen.V10.Types.Ascending

        Evergreen.V9.Types.Descending ->
            Evergreen.V10.Types.Descending


migrate_Types_SortMethod : Evergreen.V9.Types.SortMethod -> Evergreen.V10.Types.SortMethod
migrate_Types_SortMethod old =
    case old of
        Evergreen.V9.Types.Lexicographic ->
            Evergreen.V10.Types.Lexicographic

        Evergreen.V9.Types.Numeric ->
            Evergreen.V10.Types.Numeric


migrate_Types_SortState : Evergreen.V9.Types.SortState -> Evergreen.V10.Types.SortState
migrate_Types_SortState old =
    case old of
        Evergreen.V9.Types.Unsorted ->
            Evergreen.V10.Types.Unsorted

        Evergreen.V9.Types.SortedBy p0 p1 p2 ->
            Evergreen.V10.Types.SortedBy p0
                (p1 |> migrate_Types_SortDirection)
                (p2 |> migrate_Types_SortMethod)


migrate_Types_SummaryFunction : Evergreen.V9.Types.SummaryFunction -> Evergreen.V10.Types.SummaryFunction
migrate_Types_SummaryFunction old =
    case old of
        Evergreen.V9.Types.SummaryMax ->
            Evergreen.V10.Types.SummaryMax

        Evergreen.V9.Types.SummaryMin ->
            Evergreen.V10.Types.SummaryMin

        notices ->
            {- @NOTICE `SummaryMean` was added in V10.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://lamdera.com/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `SummaryMedian` was added in V10.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://lamdera.com/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `SummaryMode` was added in V10.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://lamdera.com/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_TableSnapshot : Evergreen.V9.Types.TableSnapshot -> Evergreen.V10.Types.TableSnapshot
migrate_Types_TableSnapshot old =
    { rows = old.rows
    , cols = old.cols
    , cells = old.cells
    , headerAlignments = old.headerAlignments |> Dict.map (\k -> migrate_Types_Alignment)
    , bodyAlignments = old.bodyAlignments |> Dict.map (\k -> migrate_Types_Alignment)
    , horizontalLineStyles = old.horizontalLineStyles |> Dict.map (\k -> migrate_Types_LineStyle)
    , verticalLineStyles = old.verticalLineStyles |> Dict.map (\k -> migrate_Types_LineStyle)
    , cellHorizontalStyles = old.cellHorizontalStyles |> Dict.map (\k -> migrate_Types_LineStyle)
    , cellVerticalStyles = old.cellVerticalStyles |> Dict.map (\k -> migrate_Types_LineStyle)
    }
